### PR TITLE
Update for 2018 base code changes

### PR DESCRIPTION
**Pull request by andrewda**
Would appreciate a review from as many people as possible! This should get merged in before Bunny Bots 👍 

Closes https://github.com/SouthEugeneRoboticsTeam/Robot-Base/issues/9

### CODE REVIEW

**Comment by gnawinganimal** [comment]
Would you mind if I migrated this to the kotlin gradle dsl? I started using it and its really nice.

**Comment by andrewda** [comment]
@Jamdan2 make a PR into the `2018-update` branch. I've been meaning to check that out but haven't had time!

**Review by will-hou — DISMISSED** [review]

**Review by gnawinganimal — DISMISSED** [review]
Ok, I will! Other than that, its good 👍

**Review by snowsignal — DISMISSED** [review]
Looks awesome! 👍

**Pull request merged**
